version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint
    versions:
    - 7.25.0
  - dependency-name: mongoose
    versions:
    - 5.12.5
  - dependency-name: ts-jest
    versions:
    - 26.5.5
  - dependency-name: "@types/mongoose"
    versions:
    - 5.10.5
  - dependency-name: validator
    versions:
    - 13.6.0
  - dependency-name: serverless-localstack
    versions:
    - 0.4.29
    - 0.4.30
  - dependency-name: "@micheleangioni/node-messagebrokers"
    versions:
    - 0.8.0
