version: '3.5'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017

  localstack:
    image: localstack/localstack:0.11.4
    ports:
      - "4567-4599:4567-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DATA_DIR=/tmp/localstack2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=sls-node-ts
    volumes:
      - "${TMPDIR:-/tmp/localstack2}:/tmp/localstack2"
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: sls-node-ts
