service:
  name: sls-node-ts

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'development'}
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource: [
        "*"
      ]
  environment:
    ENV: ${self:provider.stage}
    REGION: ${self:provider.region}

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          method: post
          path: graphql
  getCities:
    handler: handler.getUsers
    events:
      - http:
          method: get
          path: users
  authorizerFunc:
    handler: handler.authorizer
