service:
  name: sls-node-ts

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'development'}
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource: [
        "*"
      ]
    - Effect: 'Allow'
      Action:
        - 'SNS:Publish'
      Resource:
        !Ref SnsUserTopic
  environment:
    ENV: ${self:provider.stage}
    AWS_REGION: ${self:provider.region}
    UNDERLYING_CLIENT: 'awssns'

functions:
  graphql:
    handler: handler.enhancedGraphqlHandler
    events:
      - http:
          method: post
          path: graphql
  getUsers:
    handler: handler.enhancedGetUsers
    events:
      - http:
          method: get
          path: users
  authorizerFunc:
    handler: handler.authorizer

resources:
  Resources:
    SnsUserTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Domain Events of User Aggregate Topic
        TopicName: events_aggregate_user
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
