service:
  name: sls-node-ts

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          method: post
          path: graphql
  getCities:
    handler: handler.getUsers
    events:
      - http:
          method: get
          path: users
