name: CI Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create a Docker network
        run: docker network create sls-node-ts

      - name: Run docker-compose
        run: docker-compose -f dev/docker-compose.yaml up -d

      - name: Sleep for 120 seconds
        run: sleep 120s
        shell: bash

      - name: Checks
        run: aws dynamodb list-tables --endpoint http://localhost:4566
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Check running containers
        run: docker ps -a

      - name: Run tests
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCOUNT_ID: "000000000000"
          AWS_ACCESS_KEY_ID: dummy-access-key
          AWS_SECRET_ACCESS_KEY: dummy-secret-key
        run: npm test
